version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_minhasfinancas
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432 